config/routes.rb
NewAccount::Application.routes.draw do

  root :to       => 'demands#new'
  match '/'      => 'demands#new' 
  match '/home'  => 'demands#new' 

  resources :demands do
    member do
      post 'approve'
      post 'resend_confirm'
      get  'confirm'
    end
    collection do
      post 'multi_action'
    end
  end

  match 'auth/login',   :controller => :auth, :action => :login,  :via => :get
  match 'auth/auth',    :controller => :auth, :action => :auth,   :via => :post
  match 'auth/deauth',  :controller => :auth, :action => :deauth, :via => :get

end

app/controllers/demands_controller.rb
class DemandsController < ApplicationController

  def show
    @demand = Demand.find(params[:id]) rescue nil
    unless can_edit?(@demand)
      redirect_to :action => :new
      return
    end
  end



  def new
    @demand = Demand.new
  end



  def create
    @demand = Demand.new(params[:demand])
    @demand.session_id = session[:session_id]
    @demand.generate_token

    unless can_edit?(@demand)
      redirect_to :action => :new
      return
    end

    if ! @demand.save
      render :action => :new
      return
    end

    unless send_confirm_email(@demand)
      flash[:error] = "It seems some error occured. Email notification was probably not sent. Sorry. We'll look into that.\n"
    end

    send_admin_notification(@demand)

    sleep 1
    redirect_to :action => :show, :id => @demand.id
  end



  def edit
    @demand = Demand.find(params[:id]) rescue nil
    unless can_edit?(@demand)
      redirect_to :action => :new
      return
    end
    render :action => :new
  end



  def update
    @demand = Demand.find(params[:id]) rescue nil

    unless can_edit?(@demand)
      redirect_to :action => :new
      return
    end

    @demand.update_attributes(params[:demand])

    if ! @demand.save
      render :action => :new
      return
    end

    flash[:notice] = "The account request has been updated."

    sleep 1
    redirect_to :action => :show, :id => @demand.id
  end



  def index
    if session[:admin].blank?
      redirect_to :action => :new
    end

    @page_size = (params[:page_size].presence || session[:page_size]     || 100).to_i
    session[:page_size] = @page_size

    @page      = (params[:page].presence      || session[:page].presence || "1").to_i
    @real_tot  = Demand.count

    session[:institution_filter] = params[:institution_filter] if params.has_key?(:institution_filter)
    session[:email_filter]       = params[:email_filter]       if params.has_key?(:email_filter)
    session[:login_filter]       = params[:login_filter]       if params.has_key?(:login_filter)
    session[:country_filter]     = params[:country_filter]     if params.has_key?(:country_filter)
    session[:approved_filter]    = params[:approved_filter]    if params.has_key?(:approved_filter)
    session[:confirmed_filter]   = params[:confirmed_filter]   if params.has_key?(:confirmed_filter)
    session[:dupemail_filter]    = params[:dupemail_filter]    if params.has_key?(:dupemail_filter)

    @demands = Demand.where({})
    @demands = @demands.where(["institution like ?", "%#{session[:institution_filter]}%"]) if session[:institution_filter].present?
    @demands = @demands.where(["email like ?",       "%#{session[:email_filter]}%"])       if session[:email_filter].present?
    @demands = @demands.where(["login like ?",       "%#{session[:login_filter]}%"])       if session[:login_filter].present?
    @demands = @demands.where(["country like ?",     "%#{session[:country_filter]}%"])     if session[:country_filter].present?
    @demands = @demands.where("approved_by is not null")                            if session[:approved_filter] == "1"
    @demands = @demands.where(:approved_by => nil)                                  if session[:approved_filter] == "0"
    @demands = @demands.where("confirmed is not null")                              if session[:confirmed_filter] == "1"
    @demands = @demands.where(:confirmed => nil)                                    if session[:confirmed_filter] == "0"

    if session[:dupemail_filter].present?
       dup_emails = []
       Demand.select(:email).group(:email).count(:email).each { |e,c| dup_emails.push(e) if c > 1 }
       @demands = @demands.where(:email => dup_emails) if dup_emails.size > 0
       @demands = @demands.order([ :email, :id ])
    end

    @tot     = @demands.count

    @page    = 1 if (@page-1) * @page_size > @tot
    @demands = @demands.offset((@page-1) * @page_size).limit(@page_size).all

    session[:page]               = @page.to_s

  end



  def destroy
    @demand = Demand.find(params[:id]) rescue nil

    unless can_edit?(@demand)
      redirect_to :action => :new
      return
    end

    @demand.destroy
    flash[:notice] = "The account request has been deleted."

    if session[:admin].present?
      redirect_to :action => :index
    else
      redirect_to :action => :new
    end
  end



  def confirm
    @demand = Demand.find(params[:id]) rescue nil
    token    = params[:token] || ""
    if @demand.present? && token.present? && @demand.confirm_token == token
      @demand.confirmed = true
      @demand.save
    else
      redirect_to :root
    end
  end



  def approve
    @demand = Demand.find(params[:id]) rescue nil
    unless can_edit?(@demand) && session[:admin].present?
      redirect_to :action => :new
      return
    end

    if @demand.login.blank?
      flash[:error] = "Before approval, a 'login' name must be set."
      redirect_to :action => :edit, :id => @demand.id
      return
    end

    symbolic_result, @info, @exception_trace = approve_one(@demand)

    if symbolic_result == :all_ok
      flash.now[:notice] = "The after_approval callback was successfully invoked."
      flash.now[:notice] += "\nThe account request for '#{@demand.full}' has been approved."
      flash.now[:notice] += "\nThe user was notified of his new account."
    elsif symbolic_result == :failed_approval
      flash.now[:error] = @info.presence || ""
    elsif symbolic_result == :failed_undo_approval
      flash.now[:error] = @info.presence || ""
    elsif symbolic_result == :not_notifiable
      flash.now[:error] = @info.presence || ""
    end

  end



  def multi_action

    unless session[:admin].present?
      redirect_to :action => :new
      return
    end

    if params[:commit] =~ /approve/i
      return approve_multi
    end

    if params[:commit] =~ /fix login/i
      return fix_login_multi
    end

    if params[:commit] =~ /resend/i
      return resend_conf_multi
    end

    if params[:commit] =~ /clean not notified/i
      return clean_not_notified_multi
    end

    if params[:commit] =~ /delete/i
      return delete_multi
    end

    if params[:commit] =~ /undo approval/i
      return undo_app_multi
    end

    redirect_to :action => :index
  end



  def delete_multi

    reqids = params[:del_reqids] || []
    reqs = Demand.find(reqids)

    count = 0
    reqs.each do |req|
      count += 1 if req.destroy
    end

    flash[:notice] = "Deleted #{count} records."

    redirect_to :action => :index
  end



  def undo_app_multi

    reqids = params[:undoapp_reqids] || []
    reqs = Demand.find(reqids)

    # TODO: optimize whole process when no after_failed_user_notification() method

    @results = reqs.map do |req|
      next unless req.account_exists?
      next unless req.approved?

      puts "Undoing approval for account: #{req.full_name}"

      if req.respond_to?(:undo_approval)
        begin
          if req.undo_approval
            req.approved_by = nil
            req.approved_at = nil
            req.save
          end
          [ req, :all_ok, 'Undid approval.', nil ]
        rescue => ex
          exception_trace = "#{ex.class}: #{ex.message}\n" + ex.backtrace.join("\n")
          [ req, :failed_unapproving_account, 'ERROR: Exception when un-approving account' , exception_trace ]
        end
      else
        [ req, :no_operation, 'Warning: No support for un-approving.', nil ]
      end

    end

    @results.compact!

    render :action => :multi_action
  end



  def clean_not_notified_multi

    reqids = params[:notnotif_reqids] || []
    reqs = Demand.find(reqids)

    # TODO: optimize whole process when no after_failed_user_notification() method

    @results = reqs.map do |req|
      next unless req.account_exists?
      next if     req.approved?

      puts "Cleaning account: #{req.full_name}"

      if req.respond_to?(:after_failed_user_notification)
        begin
          req.after_failed_user_notification
          [ req, :all_ok, 'Record cleaned.', nil ]
        rescue => ex
          exception_trace = "#{ex.class}: #{ex.message}\n" + ex.backtrace.join("\n")
          [ req, :failed_cleaning_account, 'ERROR: Exception when cleaning account' , exception_trace ]
        end
      else
        [ req, :no_operation, 'Warning: No support for cleaning.', nil ]
      end

    end

    @results.compact!

    render :action => :multi_action
  end



  def resend_conf_multi

    reqids = params[:notconf_reqids] || []
    reqs = Demand.find(reqids)

    @results = reqs.map do |req|
      next if req.confirmed? || req.approved_by.present?
      print "Resending confirmation: #{req.full_name}"
      if send_confirm_email(req)
        puts ""
        [ req, :all_ok, "Resend confirmation email", nil ]
      else
        puts "=> ********* FAILED *********"
        [ req, :failed_confirm, "ERROR: Could not send confirmation email", nil ]
      end
    end

    @results.compact!

    render :action => :multi_action

  end



  def fix_login_multi

    reqids = params[:log_reqids] || []
    reqs = Demand.find(reqids)

    login_cnts = Demand.uniq_login_cnts

    @results = reqs.map do |req|

      old   = req.login
      new   = ""
      puts "Fixing: #{old}"

      email = req.email
      if email =~ /^(\w+)@/
        new = Regexp.last_match[1].downcase
      end
      new = "" if new.size < 3 || new.size > 8
      new = "" if (login_cnts[new] || 0) > 0

      if new.blank?
        new = (req.first[0,1] + req.last[0,7]).downcase
      end
      new = "" if new !~ /^[a-z][a-zA-Z0-9]+$/
      new = "" if new.size < 3 || new.size > 8
      new = "" if (login_cnts[new] || 0) > 0

      if new.blank?
          puts "  -> No changes"
        [ req, :no_change, 'No changes', nil ]
      else
        backtrace = nil
        begin
          req.update_attribute(:login, new)
          puts "  -> #{old} => #{new}"
        rescue => ex
          backtrace = ex.backtrace
        end

app/views/demands/_result_action_one.html.erb
<%
#
# Partial with these locals:
#
# demand          : demand object
# sym_res         : a result symbol
# info            : info message
# exception_trace : stack trace when error
#
%>

<h3>Result for <%= crop_text(demand.full_name) %>, <%= crop_text(demand.institution) %></h3>


<% if info.present? %>

  <% if info =~ /^error/i %>
    <div class="flash_error"><pre><%= info.to_s %></pre></div>
  <% else %>
    <pre class="comment"><%= info.to_s %></pre>
  <% end %>

<% end %>



<% if exception_trace.present? %>

  <div class="flash_error"><pre><%= exception_trace %></pre></div>

<% end %>

app/views/demands/approve.html.erb
<h1>Request Approval Result:<h1>

<% if @exception_trace.present? %>

  <h3>Here is a trace of the error.</h3>

  You might want to check the code of demands.rb, in method after_approval().<p>

  <div class="flash_error"><pre><%= @exception_trace %></pre></div>

<% elsif @info.present? %>

  <h3>Information provided by custom method after_approval()</h3>

  Some sort of report or trace was produced by your custom method:<p>

  <pre class="comment"><%= @info %></pre>

<% elsif @demand.respond_to?(:after_approval) %>

  <h3>The request was marked as 'approved' and custom code invoked.</h3>

  And some automatic operation was performed by your
  custom method after_approval(), which did not
  produce any more information that we can show here.

<% else %>

  <h3>The request was marked only as 'approved'.</h3>

  No further automatic action was taken. If you would like
  to automate further what happens, consider customizing the
  method after_approval() in the model demands.rb.

<% end %>

<p>

You can go <%= link_to "back to see the request", demand_path(@demand) %>.<br/>
You can go <%= link_to "back to the index", :action => :index %> too.

app/views/demands/confirm.html.erb
<h1>Confirmed!</h1>

Thank you. You've confirmed your email address with <%= the_organization %>.
<p>
Now it's up to the administrators to review your request
and you'll be notified if and when they approve it.
<p>

(There is nothing else to do here, you might as well have a coffee and read the news)

app/views/demands/index.html.erb
<h1>List of new account requests:</h1>

<% numpages = (((@tot > 0 ? @tot : 1)-1)/@page_size)+1 %>
<% start_i    = (@page-1)*@page_size + 1 %>
<% end_i      = start_i + @demands.size - 1 %>

<%= form_tag({:action => :multi_action}, :method => :post) do %>

<table class="index_table">

<tr>
  <th colspan="9">
    <% if @demands.count > 0 %>
      Showing records <%= start_i %> to <%= end_i %> of <%= @tot %>
      <% if @real_tot > @tot %>
        (out of <%= @real_tot %>)
      <% end %>
    <% else %>
      (No records to show)
    <% end %>
  </th>
</tr>

<% if numpages > 1 %>
  <tr><td colspan="9" class="pagelist">
  Pages: <% 1.upto(numpages) do |p| %>
    <% if @page == p %>
      <strong><%= p * @page_size %></strong>
    <% else %>
      <%= link_to "#{p * @page_size}", :page => "#{p}" %>
    <% end %>
  <% end %>
  </td></tr>
<% end %>

<tr>
  <th>Full Name</th>
  <th><%= select_all_checkbox('app_reqid') %></th>
  <th>Email</th>
  <th>Institution</th>
  <th>Country</th>
  <th><%= select_all_checkbox('log_reqid') %>&nbsp;Username</th>
  <th>Comments?</th>
  <th>Action</th>
  <th>Status
      | Not Conf: <%= select_all_checkbox('notconf_reqid') %>
      | Not Notif: <%= select_all_checkbox('notnotif_reqid') %>
  </th>
</tr>

<% email_cnts = Demand.uniq_email_cnts %>
<% login_cnts = Demand.uniq_login_cnts %>

<% prev_email = "" %>
<% @demands.each_with_index do |req,idx| %>

<% dup_email   = email_cnts[req.email.downcase] > 1 %>
<% dup_login   = login_cnts[req.login.downcase] > 1 %>
<% # dest_exists = req.account_exists? %>

<% if session[:dupemail_filter].present? && prev_email != "" && req.email.downcase != prev_email.downcase%>
  <tr><td colspan="9" style="background: black"></td></tr>
<% end %>
<% prev_email = req.email %>

<% susp_type = req.is_suspicious? %>
<% if susp_type %>
<tr class="suspicious<%= susp_type %>">
<% elsif idx % 2 == 0 %>
<tr class="index_even">
<% else %>
<tr class="index_odd">
<% end %>

  <td><%= crop_text(req.full) %></td>

  <td>
    <% if req.confirmed? && !req.approved_by.presence && !dup_email && !dup_login %>
      <%= check_box_tag 'app_reqids[]', req.id.to_s, false, :class => 'app_reqid' %>
    <% end %>
  </td>

  <td>
    <% if ! dup_email %>
      <%= crop_text(req.email) %>
    <% else %>
      <%= link_to "*", :action => :index,
         :institution_filter => "",
         :email_filter       => req.email,
         :country_filter     => "",
         :login_filter       => "",
         :approved_filter    => "",
         :confirmed_filter   => ""
      %>
      <span style="color: red"><%= crop_text(req.email) %></span>
    <% end %>
  </td>

  <td><%= crop_text(req.institution) %></td>
  <td><%= crop_text(req.country) %></td>

  <td>
    <% if ! dup_login %>
      <%= req.login %>
    <% else %>
      <%= link_to "*", :action => :index,
         :institution_filter => "",
         :email_filter       => "",
         :country_filter     => "",
         :login_filter       => req.login,
         :approved_filter    => "",
         :confirmed_filter   => ""
      %>
      <%= dup_email ? "" : check_box_tag('log_reqids[]', req.id.to_s, false, :class => 'log_reqid') %>
      <span style="color: red"><%= req.login %></span>
    <% end %>
  </td>

  <td><%= crop_text(req.comment,15) %></td>

  <td>
      <%= link_to "Show", { :action => :show, :id => req.id } , :title => "Dept: #{req.department} Pos: #{req.position}" %>
      /
      <%= link_to "Edit", :action => :edit, :id => req.id %>
      /
      <%= link_to "Del", demand_path(req), :action => :destroy, :method => :delete, :confirm => "Are you sure you want to delete the request of \"#{req.full}\" ?" %>
      <%= check_box_tag('del_reqids[]', req.id.to_s, false, :class => 'del_reqid') %>
  </td>

  <td>

     <% if req.approved_by.presence && req.approved_at.presence %>
       <%= check_box_tag 'undoapp_reqids[]', req.id.to_s, false, :class => 'undoapp_reqid' %>
       OK by: <%= req.approved_by %> at <%= req.approved_at %>
     <% elsif ! req.confirmed? %>
       <%= dup_email ? "" : check_box_tag('notconf_reqids[]', req.id.to_s, false, :class => 'notconf_reqid') %>
       (Waiting for confirmation)
     <% elsif dup_login %>
       <span style="color: red">(Conflicting name)</span>
     <% elsif dup_email %>
       <span style="color: #ff00ff">(Conflicting email)</span>
     <% elsif req.account_exists? %>
       <%= check_box_tag 'notnotif_reqids[]', req.id.to_s, false, :class => 'notnotif_reqid' %>
       <span style="color: orange">(Exist yet not notified)</span>
     <% else %>
       <%= link_to "(Approve this)", approve_demand_path(req), :method => :post,
           :confirm => "Approve the application of \"#{req.full}\" for service \"#{req.service}\" ?" %>
     <% end %>

     <% if false && (req.approved_by.blank? || req.approved_at.blank?) && dest_exists %>
        <span style="color: red">EXISTS!</span>
     <% end %>

  </td>

</tr>

<% end %>

<tr style="background: #ffffcc">
  <td colspan="3"><center><%= submit_tag "Approve Checked" %><center></td>
  <td colspan="2"></td>
  <td colspan="1"><%= submit_tag "Fix Login" %></td>
  <td colspan="1"></td>
  <td colspan="1"><%= submit_tag "Delete" %></td>
  <td colspan="1">
    <%= submit_tag "Resend Conf" %>
    <%= submit_tag "Clean Not Notified" %>
    <%= submit_tag "Undo Approval" %>
  </td>
</tr>

</table>


<% end %>

<p>

<h3>Filter table</h3>

Presets:
   <%= link_to "Clear", :action => :index,
       :institution_filter => "",
       :email_filter       => "",
       :country_filter     => "",
       :login_filter       => "",
       :approved_filter    => "",
       :confirmed_filter   => "",
       :dupemail_filter    => ""
   %>
   |
   <%= link_to "Conf but Not App", :action => :index,
       :institution_filter => "",
       :email_filter       => "",
       :country_filter     => "",
       :login_filter       => "",
       :approved_filter    => "0",
       :confirmed_filter   => "1",
       :dupemail_filter    => ""
   %>
   |
   <%= link_to "Not Conf Not App", :action => :index,
       :institution_filter => "",
       :email_filter       => "",
       :country_filter     => "",
       :login_filter       => "",
       :approved_filter    => "0",
       :confirmed_filter   => "0",
       :dupemail_filter    => ""
   %>
   <%= link_to "+ Duplicate Emails", :action => :index,
       :dupemail_filter    => "1"
   %>
<p>
Page sizes:
  <% %w( 50 100 200 500 700 1000 2000 ).each do |ps| %>
    <%= link_to ps, :action => :index,  :page_size => ps %>
  <% end %>
<p>

<%= form_tag({:action => :index}, :method => :get) do %>
<table>
<tr><td>Institution: </td><td><%= text_field_tag :institution_filter, session[:institution_filter] %> </td></tr>
<tr><td>Email:       </td><td><%= text_field_tag :email_filter,       session[:email_filter] %>       </td></tr>
<tr><td>Country:     </td><td><%= text_field_tag :country_filter,     session[:country_filter] %>     </td></tr>
<tr><td>Username:    </td><td><%= text_field_tag :login_filter,       session[:login_filter] %>       </td></tr>

<tr><td>Confirmed:</td>
  <td>
  Yes: <%= radio_button_tag :confirmed_filter, "1", session[:confirmed_filter] == '1' %>
  No:  <%= radio_button_tag :confirmed_filter, "0", session[:confirmed_filter] == '0'%>
  Any: <%= radio_button_tag :confirmed_filter, "",  session[:confirmed_filter] == '' %>
  </td>
</tr>

<tr><td>Approved:</td>
  <td>
  Yes: <%= radio_button_tag :approved_filter, "1", session[:approved_filter] == '1' %>
  No:  <%= radio_button_tag :approved_filter, "0", session[:approved_filter] == '0'%>
  Any: <%= radio_button_tag :approved_filter, "",  session[:approved_filter] == '' %>
  </td>
</tr>

<tr><th colspan="2"><%= submit_tag "Filter" %></th></tr>

</table>

<% end %>

<p>
<%= link_to "Create a new Account Request", :action => :new %>
&nbsp; &nbsp; &nbsp;
<%= link_to "De-authenticate", :controller => :auth, :action => :deauth %>

app/views/demands/multi_action.html.erb
<h1>Batch action summary results</h1>

<%
   @results.compact!
   @results.each do |tuple|
     demand    = tuple[0]
     sym_res   = tuple[1]
     info      = tuple[2]
     backtrace = tuple[3]
%>
   <%= render :partial => 'result_action_one', :locals =>
       { :demand => demand, :sym_res => sym_res, :info => info, :exception_trace => backtrace }
   %>
<% end %>

<p>

You can go <%= link_to "back to the index", :action => :index %> too.

app/views/demands/show.html.erb
<% if @exception_trace.present? %>
  <div class="flash_error"><pre><%= @exception_trace %></pre></div>
<% end %>

<h1>Account Request Summary</h1>



<% if session[:admin] %>

<h3>Editing this form:</h3>
  As an administrator, you can <%= link_to "edit", :action => :edit %> this form.

  <% if ! @demand.approved_by.present? %>

    <h3>Approving this request:</h3>

    <% if Demand.where(:login => @demand.login).count > 1 %>
      This request cannot be approved until the login name is made different from any other.
      You must <%= link_to "edit", :action => :edit %> the request.
    <% else %>
      You can also <%= link_to "approve", approve_demand_path(@demand), :method => :post, :confirm => "Approve the application of \"#{@demand.full}\" for service \"#{@demand.service}\" ?" %> this request.
    <% end %>

    <% if ! @demand.confirmed? %>
      <span style="color: red">However, note that the user has not yet confirmed the email address.</span>
    <% else %>
      The user has confirmed the email address.
    <% end %>

  <% end %>

<% else %>

<p>
  You can <%= link_to "edit", :action => :edit %> this form, but
  this option will only be available while you are using the
  same browser session you used for submitting this form
  originally. Do it now while you can!

<% end %>




<% if ! @demand.confirmed? %>

<p>
A confirmation email has been sent to the address you provided. Once you receive
it, please click on the provided link so we can confirm your identity.

<P>

If you haven't received the email, you can ask for another <%= link_to "email confirmation request", resend_confirm_demand_path(@demand), :method => :post %> to be sent to you.
</br></br>
<% end %>





You can also <%= link_to "delete", demand_path(@demand), :action => :destroy, :method => :delete, :confirm => "Are you sure you want to delete the request of \"#{@demand.full}\" ?" %> this request. No traces or backups will be kept on our servers.
</br></br>
Below is a summary of the information you provided.
<p>



<div class="form_container" style="width: 40%">

  <table class="form_table">

  <tr>
    <th>Full Name:</th>
    <td><%= @demand.full %></td>
  </tr>

  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>

  <tr>
    <th>Name of Institution/Organization:</th>
    <td><%= @demand.institution %></td>
  </tr>

  <tr>
    <th>Department:</th>
    <td><%= @demand.department %></td>
  </tr>

  <tr>
    <th>Position or role:</th>
    <td><%= @demand.position %></td>
  </tr>

  <tr>
    <th>Email address:</th>
    <td><%= @demand.email %></td>
  </tr>

  <tr>
    <th>Street Address (line 1):</th>
    <td><%= @demand.street1 %></td>
  </tr>

  <tr>
    <th>Street Address (line 2):</th>
    <td><%= @demand.street2 %></td>
  </tr>

  <tr>
    <th>City:</th>
    <td><%= @demand.city %></td>
  </tr>

  <tr>
    <th>Province/State:</th>
    <td><%= @demand.province %></td>
  </tr>

  <tr>
    <th>Country:</th>
    <td><%= @demand.country %></td>
  </tr>

  <tr>
    <th>Postal Code:</th>
    <td><%= @demand.postal_code %></td>
  </tr>

  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>

  <tr>
    <th>Prefered 'login' name:</th>
    <td><%= @demand.login.presence || "(none)" %></td>
  </tr>

  <% if @demand.comment.present? %>

  <tr>
    <th>Comments or special requests:</th>
    <td><pre class="comment"><%= @demand.comment %><pre></td>
  </tr>

  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>

  <% end %>


  <tr>
    <th>Status of request:</th>
    <td>
        <% if @demand.confirmed? %>
          Email address confirmed by user.<br>
          <% if @demand.approved_by.present? %>
            Request approved by administrator.
          <% else %>
            <span style="color: #bd2936">Request not yet approved by administrator.</span>
          <% end %>
        <% else %>
          <span style="color: #bd2936">Email address not yet confirmed.</span>
        <% end %>
    </td>
  </tr>

  </table>

</div>



<% if session[:admin].presence %>
  <p>
  You can go <%= link_to "back to Index", :action => :index %> too.
<% end %>